# -*- coding: utf-8 -*-
"""MNIST

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16f7qFLQNRL9NFeJ3L7BZ4QAWXyz0IHGG
"""

import tensorflow as tf
from tensorflow import keras

mnist=keras.datasets.mnist

(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train=x_train/255
x_test=x_test/255

model=tf.keras.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),tf.keras.layers.Dense(512, activation=tf.nn.relu), tf.keras.layers.Dense(10,activation=tf.nn.softmax)])

model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics="accuracy")

model.fit(x_train,y_train,epochs=5)

loss,accuracy=model.evaluate(x_test,y_test)

print(accuracy)